apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-node-deployment
spec:
  selector:
    matchLabels:
      app: app-node
  template:
    metadata:
      labels:
        app: app-node
    spec:
      containers:
      - name: app-nodes
        image: charleszt/app-nodejs:latest
        resources: {}
        ports:
        - containerPort: 8080
