name: pipeline CICD
on:
    push:
        branches:
            - main
            
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Autenticando no Docker Registry
              uses: docker/login-action@v2.2.0
              with:
                username: ${{ secrets.DOCKERHUB_USR }}
                password: ${{ secrets.DOCKERHUB_PWD }}
            - name: Build imagem docker
              uses: docker/build-push-action@v4.1.1
              with:
                context: ./nodejs-crud/src
                file: ./nodejs-crud/src/Dockerfile
                push: true
                tags: | 
                  charleszt/app-nodejs:${{ github.run_number }}
                  charleszt/app-nodejs:latest
    deploy:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - uses: actions/checkout@v3
        - name: Instalando cli da digitalcean
          uses: digitalocean/action-doctl@v2
          with:
            token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        - name: configurando kubeconfig na pipeline
          run: doctl kubernetes cluster kubeconfig save k8s
        - name: Atualizado imagem  
          uses: actions-hub/kubectl@master
          with:
            args: kubectl set image deployment/app-node-deployment app-nodes=charleszt/app-nodejs:${{ github.run_number }}